---
# Ansible playbook to build clasp

- name: Build Clasp from source
  hosts: all

  roles:
    - { role: kamaln7.swapfile, become: yes, tags: ["swapfile"] }
    - base-prep
    - clasp-externals
    - clasp-build
