# imported roles
- src: kamaln7.swapfile

- src: git+ssh://git@git.incidental.space/glos-ansible/clasp-externals.git
  name: clasp-externals

- src: git+ssh://git@git.incidental.space/glos-ansible/clasp-build.git
  name: clasp-build
