# imported roles
- src: kamaln7.swapfile

- src: https://github.com/wemeetagain/ansible-clasp-externals
  name: clasp-externals

- src: https://github.com/wemeetagain/ansible-clasp-build
  name: clasp-build

